# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac42f3a417678986ed52825de03cb9eac13d58d503c68928f81e9d541922099cc6b28766ce1e9091ee73592f9342fcef4622ca3347a4709946604bc493eeee8

test:
  secret_key_base: aead0f3a68670e7254eddfb153c8e23f150f2242ac9e209e5eea108abc346fcd3873da743419316a2268e7092a1cc79cec82c2a3facf68f74738ab1f42b2d318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
